name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Create test file
        run: |
          cat <<EOF > doc/testic.md
          Ovo je nas mali testic.
          EOF
      - name: Create file
        run: |
          cat <<EOF > doc/Makefile
          # Minimal makefile for Sphinx documentation
          #
          # You can set these variables from the command line, and also
          # from the environment for the first two.
          SPHINXOPTS    ?=
          SPHINXBUILD   ?= sphinx-build
          SOURCEDIR     = .
          BUILDDIR      = _build
          # Put it first so that "make" without argument is like "make help".
          help:
            @$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
          
          .PHONY: help Makefile
          
          # Catch-all target: route all unknown targets to Sphinx using the new
          # "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
          %: Makefile
            @$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
          EOF
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
